class CONSTANTS:

    # INITIAL CONDITIONS (machine)
    MACHINE_INITIAL_POSITION = [-1, 0]

    # DISPLAY
    FPS = 60

    CAR_WIDTH = 100
    CAR_LENGTH = 200
    LANE_WIDTH = 150
    SCREEN_WIDTH = LANE_WIDTH*2
    SCREEN_HEIGHT = 1000

    # SPEEDS
    VEHICLE_MOVEMENT_SPEED = 0.01
    VEHICLE_LATERAL_MOVEMENT_SPEED = 0.005

    VEHICLE_CLEARANCE = (CAR_LENGTH/LANE_WIDTH)*1.5

    # POSITION BOUNDS
    Y_MINIMUM = 0
    Y_MAXIMUM = 1


    # OPTIMIZATION
    MACHINE_CRITERIA = 80
    MACHINE_INTENT = (2, 0.0)

    T_FUTURE = 10
    T_PAST = 10

    THETA_LIMITER_X = 0.01
    THETA_LIMITER_Y = 0.01

    LOSS_THRESHOLD = 0.01


    # DIVIDE BY ZERO CATCH
    EPS = 0.0000001
