import numpy as np

class CONSTANTS:

    # INITIAL CONDITIONS (machine)
    MACHINE_INITIAL_POSITION = [-1, 0]

    # DISPLAY
    FPS = 30

    CAR_WIDTH = 100
    CAR_LENGTH = 200
    LANE_WIDTH = 150
    SCREEN_WIDTH = LANE_WIDTH*2
    SCREEN_HEIGHT = 1000

    # SPEEDS
    VEHICLE_MOVEMENT_SPEED = 0.01

    #VEHICLE_CLEARANCE = (CAR_LENGTH/LANE_WIDTH)*1.5

    # POSITION BOUNDS
    Y_MINIMUM = 0
    Y_MAXIMUM = 1


    # OPTIMIZATION

    HUMAN_INTENT = (30, 0, -1, 1)

    MACHINE_INTENT = (20, 1, 0, 1)

    ACTION_PREDICTION_MULTIPLIER = 10

    T_FUTURE = 10
    T_PAST = 10

    THETA_LIMITER_X = 0.1
    THETA_LIMITER_Y = 0.1

    LOSS_THRESHOLD = 0.01


    # DIVIDE BY ZERO CATCH
    EPS = 0.0000001
